# Generated by Django 5.1.4 on 2024-12-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанры"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Кино", "verbose_name_plural": "Кино"},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "Рейтинг", "verbose_name_plural": "Рейтинг"},
        ),
    ]
