# Generated by Django 5.1.4 on 2025-01-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
