# Generated by Django 5.1.4 on 2025-01-06 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0, message='Рейтинг не может быть отрицательным!'), django.core.validators.MaxValueValidator(10.0, message='Рейтинг не может быть больше 10')]),
        ),
    ]
